popt: poptconfig.c File Reference
poptconfig.c File Reference
#include "system.h"
#include "poptint.h"
#include <sys/stat.h>
#include <glob.h>
Functions
static void configLine (poptContext con, char *line)
int poptReadConfigFile (poptContext con, const char *fn)
Read configuration file.
int poptReadDefaultConfig (poptContext con, int useEnv)
Read default configuration from /etc/popt and $HOME/.popt.
Function Documentation
static void configLine (poptContext con, char * line) [static]
< don't show in help/usage
< don't show in help/usage
< don't show in help/usage
< arg will be saved as string
Definition at line 16 of file poptconfig.c.
References _isspaceptr, poptContext_s::appName, POPT_ARG_STRING, POPT_ARGFLAG_DOC_HIDDEN, poptAddItem(), and poptParseArgvString().
Referenced by poptReadConfigFile().
int poptReadConfigFile (poptContext con, const char * fn)
Read configuration file.
Parameters:
con context
fn file name to read
Returns:
0 on success, POPT_ERROR_ERRNO on failure
< errno set, use strerror(errno)
< errno set, use strerror(errno)
< errno set, use strerror(errno)
< errno set, use strerror(errno)
< errno set, use strerror(errno)
Definition at line 97 of file poptconfig.c.
References _isspaceptr, configLine(), and POPT_ERROR_ERRNO.
Referenced by poptReadDefaultConfig().
int poptReadDefaultConfig (poptContext con, int useEnv)
Read default configuration from /etc/popt and $HOME/.popt.
Parameters:
con context
useEnv (unused)
Returns:
0 on success, POPT_ERROR_ERRNO on failure
< errno set, use strerror(errno)
Definition at line 171 of file poptconfig.c.
References poptContext_s::appName, POPT_ERROR_ERRNO, and poptReadConfigFile().
Generated for popt by 1.5.9