#ifndef __OFED_BUILD__
#include_next <linux/autoconf.h>
#define CONFIG_INFINIBAND 1
#define CONFIG_INFINIBAND_IPOIB 1
#define CONFIG_INFINIBAND_IPOIB_CM 1
#define CONFIG_INFINIBAND_SDP 1
#define CONFIG_INFINIBAND_SRP 1
#define CONFIG_INFINIBAND_SRPT 1

#define CONFIG_INFINIBAND_USER_MAD 1
#define CONFIG_INFINIBAND_USER_ACCESS 1
#define CONFIG_INFINIBAND_ADDR_TRANS 1
#define CONFIG_INFINIBAND_USER_MEM 1
#define CONFIG_INFINIBAND_MTHCA 1

#define CONFIG_INFINIBAND_CXGB3 1
#define CONFIG_CHELSIO_T3 1
#define CONFIG_INFINIBAND_NES 1

/* CONFIG_SUNRPC_XPRT_RDMA is not set */
/* CONFIG_SUNRPC is not set */
/* CONFIG_SUNRPC_GSS is not set */
/* CONFIG_RPCSEC_GSS_KRB5 is not set */
/* CONFIG_RPCSEC_GSS_SPKM3 is not set */
/* CONFIG_NFS_FS is not set */
/* CONFIG_NFS_V3 is not set */
/* CONFIG_NFS_V3_ACL is not set */
/* CONFIG_NFS_V4 is not set */
/* CONFIG_NFS_ACL_SUPPORT is not set */
/* CONFIG_NFS_DIRECTIO is not set */
/* CONFIG_EXPORTFS is not set */
/* CONFIG_LOCKD is not set */
/* CONFIG_LOCKD_V4 is not set */
/* CONFIG_NFSD is not set */
/* CONFIG_NFSD_V2_ACL is not set */
/* CONFIG_NFSD_V3 is not set */
/* CONFIG_NFSD_V3_ACL is not set */
/* CONFIG_NFSD_V4 is not set */
/* CONFIG_NFSD_RDMA is not set */

#define CONFIG_INFINIBAND_IPOIB_DEBUG 1
#define CONFIG_INFINIBAND_ISER 1
#define CONFIG_SCSI_ISCSI_ATTRS 1
#define CONFIG_ISCSI_TCP 1

#define CONFIG_RDS 1
#define CONFIG_RDS_RDMA 1
#define CONFIG_RDS_TCP 1





#define CONFIG_MLX4_CORE 1
#define CONFIG_MLX4_EN 1
#define CONFIG_MLX4_INFINIBAND 1

#define CONFIG_MLX4_DEBUG 1




#define CONFIG_INFINIBAND_SDP_DEBUG 1


#define CONFIG_INFINIBAND_QIB 1
#define CONFIG_INFINIBAND_MTHCA_DEBUG 1


#else
#undef CONFIG_MEMTRACK
#undef CONFIG_DEBUG_INFO
#undef CONFIG_INFINIBAND
#undef CONFIG_INFINIBAND_IPOIB
#undef CONFIG_INFINIBAND_IPOIB_CM
#undef CONFIG_INFINIBAND_SDP
#undef CONFIG_INFINIBAND_SRP
#undef CONFIG_INFINIBAND_SRPT

#undef CONFIG_INFINIBAND_USER_MAD
#undef CONFIG_INFINIBAND_USER_ACCESS
#undef CONFIG_INFINIBAND_ADDR_TRANS
#undef CONFIG_INFINIBAND_USER_MEM
#undef CONFIG_INFINIBAND_MTHCA

#undef CONFIG_MLX4_CORE
#undef CONFIG_MLX4_DEBUG
#undef CONFIG_MLX4_EN
#undef CONFIG_MLX4_INFINIBAND

#undef CONFIG_INFINIBAND_IPOIB_DEBUG
#undef CONFIG_INFINIBAND_ISER
#undef CONFIG_INFINIBAND_EHCA
#undef CONFIG_INFINIBAND_EHCA_SCALING
#undef CONFIG_RDS
#undef CONFIG_RDS_RDMA
#undef CONFIG_RDS_TCP
#undef CONFIG_RDS_DEBUG
#undef CONFIG_INFINIBAND_MADEYE
#undef CONFIG_INFINIBAND_QLGC_VNIC
#undef CONFIG_INFINIBAND_QLGC_VNIC_STATS
#undef CONFIG_INFINIBAND_CXGB3
#undef CONFIG_INFINIBAND_CXGB3_DEBUG
#undef CONFIG_CHELSIO_T3
#undef CONFIG_INFINIBAND_NES
#undef CONFIG_INFINIBAND_NES_DEBUG

#undef CONFIG_SUNRPC_XPRT_RDMA
#undef CONFIG_SUNRPC
#undef CONFIG_SUNRPC_GSS
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_NFS_FS
#undef CONFIG_NFS_V3
#undef CONFIG_NFS_V3_ACL
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_ACL_SUPPORT
#undef CONFIG_NFS_DIRECTIO
#undef CONFIG_EXPORTFS
#undef CONFIG_LOCKD
#undef CONFIG_LOCKD_V4
#undef CONFIG_NFSD
#undef CONFIG_NFSD_V2_ACL
#undef CONFIG_NFSD_V3
#undef CONFIG_NFSD_V3_ACL
#undef CONFIG_NFSD_V4
#undef CONFIG_NFSD_RDMA

#undef CONFIG_INFINIBAND_IPOIB_DEBUG_DATA
#undef CONFIG_INFINIBAND_SDP_SEND_ZCOPY
#undef CONFIG_INFINIBAND_SDP_RECV_ZCOPY
#undef CONFIG_INFINIBAND_SDP_DEBUG
#undef CONFIG_INFINIBAND_SDP_DEBUG_DATA
#undef CONFIG_INFINIBAND_IPATH
#undef CONFIG_INFINIBAND_QIB
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#undef CONFIG_INFINIBAND_AMSO1100

#undef CONFIG_INFINIBAND
#define CONFIG_INFINIBAND 1
#undef CONFIG_INFINIBAND_IPOIB
#define CONFIG_INFINIBAND_IPOIB 1
#undef CONFIG_INFINIBAND_IPOIB_CM
#define CONFIG_INFINIBAND_IPOIB_CM 1
#undef CONFIG_INFINIBAND_SDP
#define CONFIG_INFINIBAND_SDP 1
#undef CONFIG_INFINIBAND_SRP
#define CONFIG_INFINIBAND_SRP 1
#undef CONFIG_INFINIBAND_SRPT
#define CONFIG_INFINIBAND_SRPT 1

#undef CONFIG_INFINIBAND_USER_MAD
#define CONFIG_INFINIBAND_USER_MAD 1
#undef CONFIG_INFINIBAND_USER_ACCESS
#define CONFIG_INFINIBAND_USER_ACCESS 1
#undef CONFIG_INFINIBAND_ADDR_TRANS
#define CONFIG_INFINIBAND_ADDR_TRANS 1
#undef CONFIG_INFINIBAND_USER_MEM
#define CONFIG_INFINIBAND_USER_MEM 1
#undef CONFIG_INFINIBAND_MTHCA
#define CONFIG_INFINIBAND_MTHCA 1
#undef CONFIG_INFINIBAND_QLGC_VNIC
#undef CONFIG_INFINIBAND_CXGB3
#define CONFIG_INFINIBAND_CXGB3 1
#undef CONFIG_CHELSIO_T3
#define CONFIG_CHELSIO_T3 1
#undef CONFIG_INFINIBAND_NES
#define CONFIG_INFINIBAND_NES 1

/* CONFIG_SUNRPC_XPRT_RDMA is not set */
/* CONFIG_SUNRPC is not set */
/* CONFIG_SUNRPC_GSS is not set */
/* CONFIG_RPCSEC_GSS_KRB5 is not set */
/* CONFIG_RPCSEC_GSS_SPKM3 is not set */
/* CONFIG_NFS_FS is not set */
/* CONFIG_NFS_V3 is not set */
/* CONFIG_NFS_V3_ACL is not set */
/* CONFIG_NFS_V4 is not set */
/* CONFIG_NFS_ACL_SUPPORT is not set */
/* CONFIG_NFS_DIRECTIO is not set */
/* CONFIG_EXPORTFS is not set */
/* CONFIG_LOCKD is not set */
/* CONFIG_LOCKD_V4 is not set */
/* CONFIG_NFSD is not set */
/* CONFIG_NFSD_V2_ACL is not set */
/* CONFIG_NFSD_V3 is not set */
/* CONFIG_NFSD_V3_ACL is not set */
/* CONFIG_NFSD_V4 is not set */
/* CONFIG_NFSD_RDMA is not set */

#undef CONFIG_INFINIBAND_IPOIB_DEBUG
#define CONFIG_INFINIBAND_IPOIB_DEBUG 1
#undef CONFIG_INFINIBAND_ISER
#define CONFIG_INFINIBAND_ISER 1
#undef CONFIG_SCSI_ISCSI_ATTRS
#define CONFIG_SCSI_ISCSI_ATTRS 1
#undef CONFIG_ISCSI_TCP
#define CONFIG_ISCSI_TCP 1
#undef CONFIG_INFINIBAND_EHCA
#undef CONFIG_RDS
#define CONFIG_RDS 1
#undef CONFIG_RDS_RDMA
#define CONFIG_RDS_RDMA 1
#undef CONFIG_RDS_TCP
#define CONFIG_RDS_TCP 1
#undef CONFIG_RDS_DEBUG
#undef CONFIG_INFINIBAND_QLGC_VNIC_STATS
#undef CONFIG_INFINIBAND_CXGB3_DEBUG
#undef CONFIG_INFINIBAND_NES_DEBUG

#undef CONFIG_MLX4_CORE
#define CONFIG_MLX4_CORE 1
#undef CONFIG_MLX4_EN
#define CONFIG_MLX4_EN 1
#undef CONFIG_MLX4_INFINIBAND
#define CONFIG_MLX4_INFINIBAND 1

#undef CONFIG_MLX4_DEBUG
#define CONFIG_MLX4_DEBUG 1

#undef CONFIG_INFINIBAND_IPOIB_DEBUG_DATA
#undef CONFIG_INFINIBAND_SDP_SEND_ZCOPY
#undef CONFIG_INFINIBAND_SDP_RECV_ZCOPY
#undef CONFIG_INFINIBAND_SDP_DEBUG
#define CONFIG_INFINIBAND_SDP_DEBUG 1
#undef CONFIG_INFINIBAND_SDP_DEBUG_DATA
#undef CONFIG_INFINIBAND_IPATH
#undef CONFIG_INFINIBAND_QIB
#define CONFIG_INFINIBAND_QIB 1
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#define CONFIG_INFINIBAND_MTHCA_DEBUG 1
#undef CONFIG_INFINIBAND_MADEYE
#undef CONFIG_INFINIBAND_AMSO1100
#endif

