dbus-cxx: DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > Class Template Reference
DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > Class Template Reference
[Local Objects, Objects]
#include <method.h>
Public Types
typedef DBusCxxPointer< Method > pointer
Public Member Functions
Method (const std::string &name)
virtual ~Method ()
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
void set_method (sigc::slot2< T_return, T_arg1, T_arg2 > slot)
virtual MethodBase::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Static Public Member Functions
static pointer create (const std::string &name)
Protected Attributes
std::string m_arg_names [2+1]
sigc::slot2< T_return, T_arg1,
T_arg2 > m_slot
Detailed Description
template<class T_return, class T_arg1, class T_arg2>
class DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
template<class T_return , class T_arg1 , class T_arg2 > typedef DBusCxxPointer<Method> DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::pointer
Reimplemented from DBus::MethodBase.
Constructor & Destructor Documentation
template<class T_return , class T_arg1 , class T_arg2 > DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::Method (const std::string & name) [inline]
template<class T_return , class T_arg1 , class T_arg2 > virtual DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::~Method () [inline, virtual]
Member Function Documentation
template<class T_return , class T_arg1 , class T_arg2 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name (size_t i) [inline, virtual]
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
template<class T_return , class T_arg1 , class T_arg2 > virtual MethodBase::pointer DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone () [inline, virtual]
Implements DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method(), and DBus::MethodBase::name().
template<class T_return , class T_arg1 , class T_arg2 > static pointer DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create (const std::string & name) [inline, static]
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method().
template<class T_return , class T_arg1 , class T_arg2 > HandlerResult DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) [inline, virtual]
Implements DBus::MethodBase.
References DBUS_CXX_DEBUG, DBus::HANDLED, and DBus::NOT_HANDLED.
template<class T_return , class T_arg1 , class T_arg2 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect (int space_depth = 0) const [inline, virtual]
Returns a DBus XML description of this interface.
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::MethodBase::name().
template<class T_return , class T_arg1 , class T_arg2 > virtual void DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name (size_t i, const std::string & name) [inline, virtual]
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
template<class T_return , class T_arg1 , class T_arg2 > void DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_method (sigc::slot2< T_return, T_arg1, T_arg2 > slot) [inline]
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot.
Member Data Documentation
template<class T_return , class T_arg1 , class T_arg2 > std::string DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::m_arg_names[2+1] [protected]
template<class T_return , class T_arg1 , class T_arg2 > sigc::slot2<T_return, T_arg1,T_arg2> DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::m_slot [protected]
The documentation for this class was generated from the following file:
method.h