dbus-cxx: DBus::SignalMessage Class Reference
DBus::SignalMessage Class Reference
[DBus Messages]
Represents a DBus signal message.
#include <signalmessage.h>
Public Types
typedef DBusCxxPointer
< SignalMessage > pointer
typedef DBusCxxPointer< const
SignalMessage > const_pointer
typedef DBusCxxWeakPointer
< SignalMessage > weak_pointer
Public Member Functions
bool set_path (const std::string &p)
Path path () const
bool has_path (const std::string &p) const
std::vector< std::string > path_decomposed () const
bool set_interface (const std::string &i)
const char * interface () const
bool has_interface (const std::string &i) const
bool set_member (const std::string &m)
const char * member () const
bool has_member (const std::string &m) const
bool operator== (const SignalMessage &) const
Static Public Member Functions
static pointer create (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::pointer msg)
static const_pointer create (Message::const_pointer msg)
static pointer create (const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
Protected Member Functions
SignalMessage (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
SignalMessage (Message::pointer msg)
SignalMessage (Message::const_pointer msg)
SignalMessage (const std::string &name)
SignalMessage (const std::string &path, const std::string &interface, const std::string &name)
Detailed Description
Represents a DBus signal message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for a signal message that is received from a signal or transmitted on signal emission.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
typedef DBusCxxPointer<const SignalMessage> DBus::SignalMessage::const_pointer
Reimplemented from DBus::Message.
Examples:
signal_receiver.cpp.
typedef DBusCxxPointer<SignalMessage> DBus::SignalMessage::pointer
Reimplemented from DBus::Message.
typedef DBusCxxWeakPointer<SignalMessage> DBus::SignalMessage::weak_pointer
Reimplemented from DBus::Message.
Constructor & Destructor Documentation
DBus::SignalMessage::SignalMessage (DBusMessage * cobj = NULL, CreateMethod m = CREATE_ALIAS) [protected]
References create().
Referenced by create().
DBus::SignalMessage::SignalMessage (Message::pointer msg) [protected]
References DBus::SIGNAL_MESSAGE.
DBus::SignalMessage::SignalMessage (Message::const_pointer msg) [protected]
References DBus::SIGNAL_MESSAGE.
DBus::SignalMessage::SignalMessage (const std::string & name) [protected]
References set_member().
DBus::SignalMessage::SignalMessage (const std::string & path, const std::string & interface, const std::string & name) [protected]
References DBus::Message::m_cobj.
Member Function Documentation
SignalMessage::pointer DBus::SignalMessage::create (const std::string & path, const std::string & interface, const std::string & name) [static]
References SignalMessage().
SignalMessage::pointer DBus::SignalMessage::create (const std::string & name) [static]
References SignalMessage().
SignalMessage::const_pointer DBus::SignalMessage::create (Message::const_pointer msg) [static]
References SignalMessage().
SignalMessage::pointer DBus::SignalMessage::create (Message::pointer msg) [static]
References SignalMessage().
SignalMessage::pointer DBus::SignalMessage::create (DBusMessage * cobj = NULL, CreateMethod m = CREATE_ALIAS) [static]
Reimplemented from DBus::Message.
References SignalMessage().
Referenced by DBus::signal_proxy_base::matches(), and SignalMessage().
bool DBus::SignalMessage::has_interface (const std::string & i) const
References DBus::Message::m_cobj.
bool DBus::SignalMessage::has_member (const std::string & m) const
References DBus::Message::m_cobj.
bool DBus::SignalMessage::has_path (const std::string & p) const
References DBus::Message::m_cobj.
const char * DBus::SignalMessage::interface () const
References DBus::Message::m_cobj.
Referenced by operator==().
const char * DBus::SignalMessage::member () const
References DBus::Message::m_cobj.
Referenced by operator==().
bool DBus::SignalMessage::operator== (const SignalMessage & m) const
References interface(), DBus::Message::m_cobj, and member().
Path DBus::SignalMessage::path () const
References DBus::Message::m_cobj.
std::vector< std::string > DBus::SignalMessage::path_decomposed () const
References DBus::Message::m_cobj.
bool DBus::SignalMessage::set_interface (const std::string & i)
References DBus::Message::m_cobj.
bool DBus::SignalMessage::set_member (const std::string & m)
References DBus::Message::m_cobj.
Referenced by SignalMessage().
bool DBus::SignalMessage::set_path (const std::string & p)
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
signalmessage.h
signalmessage.cpp