dbus-cxx: DBus::Error Class Reference
DBus::Error Class Reference
[Errors]
Base class of a hierarchy of error objects thrown when exceptional conditions occur.
#include <error.h>
Inherits std::exception.
Public Types
typedef DBusCxxPointer< Error > pointer
Public Member Functions
~Error () throw ()
const char * what () const throw ()
const char * name () const
const char * message () const
void set (const char *name, const char *message)
parameters MUST be static strings
bool is_set () const
operator bool () const
DBusError * cobj ()
Static Public Member Functions
static pointer create ()
static pointer create (DBusError *cobj)
static pointer create (const char *name, const char *message)
static pointer create (Message &)
Protected Member Functions
Error ()
Error (DBusError *cobj)
Error (const char *name, const char *message=NULL)
Error (Message &)
Protected Attributes
DBusError m_cobj
Detailed Description
Base class of a hierarchy of error objects thrown when exceptional conditions occur.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
typedef DBusCxxPointer<Error> DBus::Error::pointer
Constructor & Destructor Documentation
DBus::Error::Error () [protected]
References m_cobj.
Referenced by create().
DBus::Error::Error (DBusError * cobj) [protected]
References m_cobj.
DBus::Error::Error (const char * name, const char * message = NULL) [protected]
References m_cobj.
DBus::Error::Error (Message & m) [protected]
References DBus::Message::cobj(), and m_cobj.
DBus::Error::~Error () throw ()
References m_cobj.
Member Function Documentation
DBusError * DBus::Error::cobj ()
References m_cobj.
Error::pointer DBus::Error::create (Message & message) [static]
References Error().
Error::pointer DBus::Error::create (const char * name, const char * message) [static]
References Error().
Error::pointer DBus::Error::create (DBusError * cobj) [static]
References Error().
Error::pointer DBus::Error::create () [static]
References Error().
bool DBus::Error::is_set () const
References m_cobj.
Referenced by operator bool().
const char * DBus::Error::message () const
References m_cobj.
const char * DBus::Error::name () const
References m_cobj.
DBus::Error::operator bool () const
References is_set().
void DBus::Error::set (const char * name, const char * message)
parameters MUST be static strings
References m_cobj.
const char * DBus::Error::what () const throw ()
References m_cobj.
Member Data Documentation
DBusError DBus::Error::m_cobj [protected]
Referenced by cobj(), Error(), is_set(), message(), name(), set(), what(), and ~Error().
The documentation for this class was generated from the following files:
error.h
error.cpp