dbus-cxx: DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
[Objects, Proxy]
#include <methodproxy.h>
Public Types
typedef DBusCxxPointer
< MethodProxy > pointer
Public Member Functions
MethodProxy (const std::string &name)
T_return operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4, T_arg5 _val_5, T_arg6 _val_6, T_arg7 _val_7)
Static Public Member Functions
static pointer create (const std::string &name)
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7>
class DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Examples:
calculator_client.cpp, calculator_watcher.cpp, caller_dispatched.cpp, caller_object.cpp, hal_proxy.cpp, and signal_receiver_object.cpp.
Member Typedef Documentation
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7> typedef DBusCxxPointer<MethodProxy> DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::pointer
Reimplemented from DBus::MethodProxyBase.
Constructor & Destructor Documentation
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7> DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::MethodProxy (const std::string & name) [inline]
Referenced by DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::create(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::create(), and DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
Member Function Documentation
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7> static pointer DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & name) [inline, static]
Reimplemented from DBus::MethodProxyBase.
References DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::MethodProxy().
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7> T_return DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4, T_arg5 _val_5, T_arg6 _val_6, T_arg7 _val_7) [inline]
References DBus::MethodProxyBase::call(), DBus::MethodProxyBase::create_call_message(), DBUS_CXX_DEBUG, and DBus::MethodProxyBase::m_name.
The documentation for this class was generated from the following file:
methodproxy.h