dbus-cxx: DBus::ErrorMessage Class Reference
DBus::ErrorMessage Class Reference
[DBus Messages]
Represents a DBus Error message.
#include <errormessage.h>
Public Types
typedef DBusCxxPointer
< ErrorMessage > pointer
typedef DBusCxxWeakPointer
< ErrorMessage > weak_pointer
Public Member Functions
const char * name () const
bool set_name (const std::string &n)
bool operator== (const ErrorMessage &) const
Static Public Member Functions
static pointer create ()
static pointer create (DBusMessage *cobj)
static pointer create (Message::pointer msg)
static pointer create (Message::pointer msg, const std::string &name, const std::string &message)
Protected Member Functions
ErrorMessage ()
ErrorMessage (DBusMessage *cobj)
ErrorMessage (Message::pointer msg)
ErrorMessage (Message::pointer msg, const std::string &name, const std::string &message)
Detailed Description
Represents a DBus Error message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for an error message.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
typedef DBusCxxPointer<ErrorMessage> DBus::ErrorMessage::pointer
Reimplemented from DBus::Message.
Examples:
caller_raw.cpp.
typedef DBusCxxWeakPointer<ErrorMessage> DBus::ErrorMessage::weak_pointer
Reimplemented from DBus::Message.
Constructor & Destructor Documentation
DBus::ErrorMessage::ErrorMessage () [protected]
References DBus::Message::m_cobj.
Referenced by create().
DBus::ErrorMessage::ErrorMessage (DBusMessage * cobj) [protected]
References create(), and DBus::Message::m_cobj.
DBus::ErrorMessage::ErrorMessage (Message::pointer msg) [protected]
References DBus::ERROR_MESSAGE, and DBus::Message::m_cobj.
DBus::ErrorMessage::ErrorMessage (Message::pointer msg, const std::string & name, const std::string & message) [protected]
References DBus::Message::m_cobj.
Member Function Documentation
ErrorMessage::pointer DBus::ErrorMessage::create (Message::pointer msg, const std::string & name, const std::string & message) [static]
References ErrorMessage().
ErrorMessage::pointer DBus::ErrorMessage::create (Message::pointer msg) [static]
References ErrorMessage().
ErrorMessage::pointer DBus::ErrorMessage::create (DBusMessage * cobj) [static]
References ErrorMessage().
ErrorMessage::pointer DBus::ErrorMessage::create () [static]
Examples:
caller_raw.cpp.
References ErrorMessage().
Referenced by ErrorMessage().
const char * DBus::ErrorMessage::name () const
References DBus::Message::m_cobj.
Referenced by operator==().
bool DBus::ErrorMessage::operator== (const ErrorMessage & m) const
References DBus::Message::m_cobj, and name().
bool DBus::ErrorMessage::set_name (const std::string & n)
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
errormessage.h
errormessage.cpp