dbus-cxx: DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil > Class Template Reference
DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil > Class Template Reference
[Objects, Proxy]
#include <methodproxy.h>
Public Types
typedef DBusCxxPointer
< MethodProxy > pointer
Public Member Functions
MethodProxy (const std::string &name)
T_return operator() (T_arg1 _val_1)
Static Public Member Functions
static pointer create (const std::string &name)
Detailed Description
template<class T_return, class T_arg1>
class DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
template<class T_return , class T_arg1 > typedef DBusCxxPointer<MethodProxy> DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::pointer
Reimplemented from DBus::MethodProxyBase.
Constructor & Destructor Documentation
template<class T_return , class T_arg1 > DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::MethodProxy (const std::string & name) [inline]
Member Function Documentation
template<class T_return , class T_arg1 > static pointer DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::create (const std::string & name) [inline, static]
Reimplemented from DBus::MethodProxyBase.
References DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::MethodProxy().
template<class T_return , class T_arg1 > T_return DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator() (T_arg1 _val_1) [inline]
References DBus::MethodProxyBase::call(), DBus::MethodProxyBase::create_call_message(), DBUS_CXX_DEBUG, and DBus::MethodProxyBase::m_name.
The documentation for this class was generated from the following file:
methodproxy.h