dbus-cxx: DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > Class Template Reference
DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > Class Template Reference
[Signals, Proxy]
Subclass of the numbered sigc::signal templates.
#include <signal_proxy.h>
Public Types
typedef DBusCxxPointer
< signal_proxy > pointer
Public Member Functions
signal_proxy (const std::string &interface, const std::string &name)
signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy (const std::string &interface, const std::string &name, const signal_proxy &src)
signal_proxy (const std::string &path, const std::string &interface, const std::string &name, const signal_proxy &src)
virtual signal_base::pointer clone ()
Static Public Member Functions
static pointer create (const std::string &interface, const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
static pointer create (const std::string &interface, const std::string &name, const signal_proxy &src)
static pointer create (const std::string &path, const std::string &interface, const std::string &name, const signal_proxy &src)
Protected Member Functions
virtual HandlerResult on_dbus_incoming (SignalMessage::const_pointer msg)
Detailed Description
template<class T_return, class T_arg1, class T_arg2>
class DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >
Subclass of the numbered sigc::signal templates.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
template<class T_return , class T_arg1 , class T_arg2 > typedef DBusCxxPointer<signal_proxy> DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::pointer
Reimplemented from DBus::signal_proxy_base.
Constructor & Destructor Documentation
template<class T_return , class T_arg1 , class T_arg2 > DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal_proxy (const std::string & interface, const std::string & name) [inline]
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 > DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal_proxy (const std::string & path, const std::string & interface, const std::string & name) [inline]
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 > DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal_proxy (const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > & src) [inline]
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 > DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal_proxy (const std::string & path, const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > & src) [inline]
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
Member Function Documentation
template<class T_return , class T_arg1 , class T_arg2 > virtual signal_base::pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone () [inline, virtual]
Implements DBus::signal_proxy_base.
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create (const std::string & path, const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > & src) [inline, static]
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create (const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil > & src) [inline, static]
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create (const std::string & path, const std::string & interface, const std::string & name) [inline, static]
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create (const std::string & interface, const std::string & name) [inline, static]
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 > virtual HandlerResult DBus::signal_proxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::on_dbus_incoming (SignalMessage::const_pointer msg) [inline, protected, virtual]
References DBus::HANDLED, and DBus::NOT_HANDLED.
The documentation for this class was generated from the following file:
signal_proxy.h