dbus-cxx: DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
#include <methodproxy.h>
Public Types
typedef DBusCxxPointer
< MethodProxy > pointer
Public Member Functions
MethodProxy (const std::string &name)
void operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4)
Static Public Member Functions
static pointer create (const std::string &name)
template<class T_arg1, class T_arg2, class T_arg3, class T_arg4>
class DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >
Member Typedef Documentation
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > typedef DBusCxxPointer<MethodProxy> DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::pointer
Reimplemented from DBus::MethodProxyBase.
Constructor & Destructor Documentation
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::MethodProxy (const std::string & name) [inline]
Member Function Documentation
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > static pointer DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create (const std::string & name) [inline, static]
Reimplemented from DBus::MethodProxyBase.
References DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::MethodProxy().
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > void DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4) [inline]
References DBus::MethodProxyBase::call(), DBus::MethodProxyBase::create_call_message(), DBUS_CXX_DEBUG, and DBus::MethodProxyBase::m_name.
The documentation for this class was generated from the following file:
methodproxy.h