dbus-cxx: DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
[Local Objects, Objects]
#include <method.h>
Public Types
typedef DBusCxxPointer< Method > pointer
Public Member Functions
Method (const std::string &name)
virtual ~Method ()
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
void set_method (sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot)
virtual MethodBase::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Static Public Member Functions
static pointer create (const std::string &name)
Protected Attributes
std::string m_arg_names [7+1]
sigc::slot7< T_return, T_arg1,
T_arg2, T_arg3, T_arg4, T_arg5,
T_arg6, T_arg7 > m_slot
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7>
class DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > typedef DBusCxxPointer<Method> DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::pointer
Reimplemented from DBus::MethodBase.
Constructor & Destructor Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method (const std::string & name) [inline]
Referenced by DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::create(), and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::~Method () [inline, virtual]
Member Function Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name (size_t i) [inline, virtual]
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual MethodBase::pointer DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone () [inline, virtual]
Implements DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method(), and DBus::MethodBase::name().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > static pointer DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & name) [inline, static]
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > HandlerResult DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) [inline, virtual]
Implements DBus::MethodBase.
References DBUS_CXX_DEBUG, DBus::HANDLED, and DBus::NOT_HANDLED.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect (int space_depth = 0) const [inline, virtual]
Returns a DBus XML description of this interface.
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::MethodBase::name().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual void DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name (size_t i, const std::string & name) [inline, virtual]
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > void DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method (sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot) [inline]
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot.
Member Data Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names[7+1] [protected]
Referenced by DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > sigc::slot7<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot [protected]
Referenced by DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::set_method(), and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method().
The documentation for this class was generated from the following file:
method.h