dbus-cxx: DBus::MethodProxyBase Class Reference
DBus::MethodProxyBase Class Reference
[Objects, Proxy]
#include <methodproxybase.h>
Public Types
typedef DBusCxxPointer
< MethodProxyBase > pointer
Public Member Functions
~MethodProxyBase ()
InterfaceProxy * interface () const
const std::string & name () const
void set_name (const std::string &name)
CallMessage::pointer create_call_message () const
ReturnMessage::const_pointer call (CallMessage::const_pointer, int timeout_milliseconds=-1) const
PendingCall::pointer call_async (CallMessage::const_pointer, int timeout_milliseconds=-1) const
sigc::signal< void, const
std::string &, const
std::string & > signal_name_changed ()
Static Public Member Functions
static pointer create (const std::string &name)
Protected Member Functions
MethodProxyBase (const std::string &name)
MethodProxyBase (const MethodProxyBase &other)
Protected Attributes
InterfaceProxy * m_interface
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const
std::string &, const
std::string & > m_signal_name_changed
Friends
class InterfaceProxy
Detailed Description
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
typedef DBusCxxPointer<MethodProxyBase> DBus::MethodProxyBase::pointer
Reimplemented in DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, and DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >.
Constructor & Destructor Documentation
DBus::MethodProxyBase::MethodProxyBase (const std::string & name) [protected]
References m_name_mutex.
Referenced by create().
DBus::MethodProxyBase::MethodProxyBase (const MethodProxyBase & other) [protected]
References m_name_mutex.
DBus::MethodProxyBase::~MethodProxyBase ()
References m_name_mutex.
Member Function Documentation
ReturnMessage::const_pointer DBus::MethodProxyBase::call (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_interface.
Referenced by DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), and DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()().
PendingCall::pointer DBus::MethodProxyBase::call_async (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_interface.
MethodProxyBase::pointer DBus::MethodProxyBase::create (const std::string & name) [static]
Reimplemented in DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, and DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >.
References MethodProxyBase().
CallMessage::pointer DBus::MethodProxyBase::create_call_message () const
References m_interface, and m_name.
Referenced by DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), and DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()().
InterfaceProxy * DBus::MethodProxyBase::interface () const
References m_interface.
const std::string & DBus::MethodProxyBase::name () const
References m_name.
void DBus::MethodProxyBase::set_name (const std::string & name)
References m_name, m_name_mutex, and m_signal_name_changed.
sigc::signal< void, const std::string &, const std::string & > DBus::MethodProxyBase::signal_name_changed ()
References m_signal_name_changed.
Friends And Related Function Documentation
friend class InterfaceProxy [friend]
Member Data Documentation
InterfaceProxy* DBus::MethodProxyBase::m_interface [protected]
Referenced by call(), call_async(), create_call_message(), and interface().
std::string DBus::MethodProxyBase::m_name [protected]
Referenced by create_call_message(), name(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()(), and set_name().
pthread_mutex_t DBus::MethodProxyBase::m_name_mutex [protected]
Ensures that the name doesn't change while the name changed signal is emitting.
Referenced by MethodProxyBase(), set_name(), and ~MethodProxyBase().
sigc::signal<void,const std::string&, const std::string&> DBus::MethodProxyBase::m_signal_name_changed [protected]
Referenced by set_name(), and signal_name_changed().
The documentation for this class was generated from the following files:
methodproxybase.h
methodproxybase.cpp