dbus-cxx: DBus::CallMessage Class Reference
DBus::CallMessage Class Reference
[DBus Messages]
Represents a DBus call message.
#include <callmessage.h>
Public Types
typedef DBusCxxPointer
< CallMessage > pointer
typedef DBusCxxPointer< const
CallMessage > const_pointer
typedef DBusCxxWeakPointer
< CallMessage > weak_pointer
Public Member Functions
bool set_path (const std::string &p)
Path path () const
bool has_path (const std::string &p) const
std::vector< std::string > path_decomposed () const
bool set_interface (const std::string &i)
const char * interface () const
bool has_interface (const std::string &i) const
bool set_member (const std::string &m)
const char * member () const
bool has_member (const std::string &m) const
const char * signature () const
bool has_signature (const std::string &signature) const
bool operator== (const CallMessage &) const
void set_no_reply (bool no_reply=true)
bool expects_reply () const
Static Public Member Functions
static pointer create ()
static pointer create (DBusMessage *cobj)
static pointer create (Message::pointer msg)
static const_pointer create (Message::const_pointer msg)
static pointer create (const std::string &dest, const std::string &path, const std::string &iface, const std::string &method)
static pointer create (const std::string &path, const std::string &iface, const std::string &method)
static pointer create (const std::string &path, const std::string &method)
Protected Member Functions
CallMessage ()
CallMessage (DBusMessage *cobj)
CallMessage (Message::pointer msg)
CallMessage (Message::const_pointer msg)
CallMessage (const std::string &dest, const std::string &path, const std::string &iface, const std::string &method)
CallMessage (const std::string &path, const std::string &iface, const std::string &method)
CallMessage (const std::string &path, const std::string &method)
Detailed Description
Represents a DBus call message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for a call message.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
typedef DBusCxxPointer<const CallMessage> DBus::CallMessage::const_pointer
Reimplemented from DBus::Message.
typedef DBusCxxPointer<CallMessage> DBus::CallMessage::pointer
Reimplemented from DBus::Message.
Examples:
callee_raw.cpp, and caller_raw.cpp.
typedef DBusCxxWeakPointer<CallMessage> DBus::CallMessage::weak_pointer
Reimplemented from DBus::Message.
Constructor & Destructor Documentation
DBus::CallMessage::CallMessage () [protected]
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
Referenced by create().
DBus::CallMessage::CallMessage (DBusMessage * cobj) [protected]
References create(), and DBus::Message::m_cobj.
DBus::CallMessage::CallMessage (Message::pointer msg) [protected]
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
DBus::CallMessage::CallMessage (Message::const_pointer msg) [protected]
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
DBus::CallMessage::CallMessage (const std::string & dest, const std::string & path, const std::string & iface, const std::string & method) [protected]
References DBus::Message::m_cobj, and DBus::Message::m_valid.
DBus::CallMessage::CallMessage (const std::string & path, const std::string & iface, const std::string & method) [protected]
References DBus::Message::m_cobj, and DBus::Message::m_valid.
DBus::CallMessage::CallMessage (const std::string & path, const std::string & method) [protected]
References DBus::Message::m_cobj, and DBus::Message::m_valid.
Member Function Documentation
CallMessage::pointer DBus::CallMessage::create (const std::string & path, const std::string & method) [static]
References CallMessage().
CallMessage::pointer DBus::CallMessage::create (const std::string & path, const std::string & iface, const std::string & method) [static]
References CallMessage().
CallMessage::pointer DBus::CallMessage::create (const std::string & dest, const std::string & path, const std::string & iface, const std::string & method) [static]
References CallMessage().
CallMessage::const_pointer DBus::CallMessage::create (Message::const_pointer msg) [static]
References CallMessage().
CallMessage::pointer DBus::CallMessage::create (Message::pointer msg) [static]
References CallMessage().
CallMessage::pointer DBus::CallMessage::create (DBusMessage * cobj) [static]
References CallMessage().
CallMessage::pointer DBus::CallMessage::create () [static]
Examples:
callee_raw.cpp, and caller_raw.cpp.
References CallMessage().
Referenced by CallMessage().
bool DBus::CallMessage::expects_reply () const
References DBus::Message::m_cobj.
bool DBus::CallMessage::has_interface (const std::string & i) const
References DBus::Message::m_cobj.
bool DBus::CallMessage::has_member (const std::string & m) const
References DBus::Message::m_cobj.
bool DBus::CallMessage::has_path (const std::string & p) const
References DBus::Message::m_cobj.
bool DBus::CallMessage::has_signature (const std::string & signature) const
References DBus::Message::m_cobj.
const char * DBus::CallMessage::interface () const
References DBus::Message::m_cobj.
Referenced by operator==().
const char * DBus::CallMessage::member () const
References DBus::Message::m_cobj.
Referenced by operator==().
bool DBus::CallMessage::operator== (const CallMessage & m) const
References interface(), DBus::Message::m_cobj, and member().
Path DBus::CallMessage::path () const
References DBus::Message::m_cobj.
std::vector< std::string > DBus::CallMessage::path_decomposed () const
References DBus::Message::m_cobj.
bool DBus::CallMessage::set_interface (const std::string & i)
References DBus::Message::m_cobj.
bool DBus::CallMessage::set_member (const std::string & m)
References DBus::Message::m_cobj.
void DBus::CallMessage::set_no_reply (bool no_reply = true)
References DBus::Message::m_cobj.
bool DBus::CallMessage::set_path (const std::string & p)
References DBus::Message::m_cobj.
const char * DBus::CallMessage::signature () const
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
callmessage.h
callmessage.cpp