dbus-cxx: DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > Class Template Reference
DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > Class Template Reference
[Signals, Local Objects]
Subclass of the numbered sigc::signal templates.
#include <dbus_signal.h>
Public Types
typedef DBusCxxPointer< signal > pointer
Public Member Functions
signal (const std::string &interface, const std::string &name)
signal (const std::string &path, const std::string &interface, const std::string &name)
signal (const std::string &interface, const std::string &name, const signal &src)
signal (const std::string &path, const std::string &interface, const std::string &name, const signal &src)
virtual signal_base::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Static Public Member Functions
static pointer create (const std::string &interface, const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
static pointer create (const std::string &interface, const std::string &name, const signal &src)
static pointer create (const std::string &path, const std::string &interface, const std::string &name, const signal &src)
Protected Member Functions
T_return internal_callback (T_arg1 arg1, T_arg2 arg2, T_arg3 arg3, T_arg4 arg4, T_arg5 arg5, T_arg6 arg6)
Protected Attributes
std::string m_arg_names [6]
sigc::connection m_internal_callback_connection
Friends
class Interface
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6>
class DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >
Subclass of the numbered sigc::signal templates.
This class defines a subclass of the sigc::signal types and can be used as its parent. The key difference is that when the signal is emitted a DBus signal message is created using the parameters of the signal emission and transmitted via the dbus in addition to any local signal propagation that may take place.
Author:
Rick L Vinyard Jr <rvinyard@cs.nmsu.edu>
Member Typedef Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > typedef DBusCxxPointer<signal> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::pointer
Reimplemented from DBus::signal_base.
Constructor & Destructor Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal (const std::string & interface, const std::string & name) [inline]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_internal_callback_connection.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal (const std::string & path, const std::string & interface, const std::string & name) [inline]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_internal_callback_connection.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal (const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) [inline]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal (const std::string & path, const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) [inline]
Member Function Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name (size_t i) [inline, virtual]
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual signal_base::pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone () [inline, virtual]
Implements DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & path, const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) [inline, static]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) [inline, static]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & path, const std::string & interface, const std::string & name) [inline, static]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & interface, const std::string & name) [inline, static]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > T_return DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::internal_callback (T_arg1 arg1, T_arg2 arg2, T_arg3 arg3, T_arg4 arg4, T_arg5 arg5, T_arg6 arg6) [inline, protected]
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), DBUS_CXX_DEBUG, DBus::signal_base::handle_dbus_outgoing(), DBus::signal_base::m_destination, DBus::signal_base::m_interface, DBus::signal_base::m_name, and DBus::signal_base::m_path.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect (int space_depth = 0) const [inline, virtual]
Returns a DBus XML description of this interface.
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::signal_base::name().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual void DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name (size_t i, const std::string & name) [inline, virtual]
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
Friends And Related Function Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > friend class Interface [friend]
Member Data Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::m_arg_names[6] [protected]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > sigc::connection DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::m_internal_callback_connection [protected]
The documentation for this class was generated from the following file:
dbus_signal.h