#!/bin/sh

PIDFILE=/var/run/gdm.pid
if test '!' -f $PIDFILE ; then
	echo "$PIDFILE doesn't exist, perhaps GDM isn't running"
	exit 1
fi
# exec the kill to get the correct return code
echo "Not supported"

