#!/bin/sh
#
# vim:set noet ts=4:
#
# ibus-anthy - The Anthy engine for IBus
#
# Copyright (c) 2007-2008 Peng Huang <shawn.p.huang@gmail.com>
# Copyright (c) 2007-2010 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

prefix=/usr
datarootdir=${prefix}/share
exec_prefix=/usr
libexecdir=/usr/libexec
pyexecdir=${exec_prefix}/lib64/python2.6/site-packages
export PYTHONPATH=${exec_prefix}/lib64/python2.6/site-packages:$PYTHONPATH
export IBUS_PREFIX=/usr
export IBUS_ANTHY_PKGDATADIR=${prefix}/share/ibus-anthy
export LIBEXECDIR=$libexecdir
exec python ${prefix}/share/ibus-anthy/engine/main.py $@

